name: Create GitHub Release

on:
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Extract short SHA
        id: extract_sha
        run: |
          git rev-parse --short=7 HEAD > short_sha.txt
          echo "short_sha=$(cat short_sha.txt)" >> $GITHUB_OUTPUT
      
